# Generated by Django 4.0.1 on 2022-01-29 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_comment_snippet_tag_remove_review_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 1, 29, 0, 20, 55, 329393)),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet_entrydate',
            field=models.DateField(verbose_name=datetime.datetime(2022, 1, 29, 0, 20, 55, 329393)),
        ),
    ]
